high_cadence: false
apply_custom_mask_after_S1: true
run_jwst_S2: true
run_eureka_S2: true
run_eureka_S3: true

paths:
  topdir: /path/to/top/dir
  inputdir: /path/to/input/dir
  outputdir: /path/to/output/dir
  ecf_dir: /path/to/ecf/dir

crds_settings:
  server_url: https://jwst-crds.stsci.edu
  context: jwst-operational
  path: ~/crds_cache
  mode: auto

ecf_settings:
  S1:
    example_key: example_value
  S2:

custom_mask:
  S1:
  - [x, y]
  S2:
  - [x, y]
  - [x2, y2]
  S3:
  - []
