paths:
  topdir: /path/to/top/dir
  inputdir: /path/to/input/dir
  outputdir: /path/to/output/dir
  ecf_dir: /path/to/ecf/dir

ecf_settings:
  example_key: example_value

custom_mask:
  S1:
  - [x, y]
  S2:
  - [x, y]
  - [x2, y2]
  S3:
  - []
